apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: ticket-frontend
          image: ticket-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80

